import { NextRequest, NextResponse } from "next/server";
import { getCurrentUser } from "@/lib/auth";
import { requireCsrf } from "@/lib/csrf";
import { checksum } from "@/lib/crypto";
import { db } from "@/lib/db";
import { env } from "@/lib/env";
import { errorResponse } from "@/lib/http";
import { publishToLinkedIn } from "@/lib/services/linkedin";
import { readAsset } from "@/lib/services/assets";
import { audit } from "@/lib/audit";

export async function POST(request: NextRequest, { params }: { params: Promise<{ id: string }> }) { try { const user = await getCurrentUser(request); if (!user) throw new Error("UNAUTHORIZED"); await requireCsrf(request); const { id } = await params; const draft = await db.draft.findFirst({ where: { id, userId: user.id }, include: { assets: true, story: true } }); if (!draft) return NextResponse.json({ error: "Draft not found." }, { status: 404 }); const tags = JSON.parse(draft.hashtags) as string[]; const currentChecksum = checksum(`${draft.body}\n${tags.join(" ")}`); if (draft.status !== "APPROVED" || draft.reviewedChecksum !== currentChecksum) return NextResponse.json({ error: "Draft must be approved and unchanged before publishing." }, { status: 409 }); const payload = { commentary: `${draft.body}\n\n${tags.join(" ")}`, visibility: "PUBLIC", sourceUrl: draft.story.canonicalUrl }; if (env.CONTENT_STUDIO_PUBLISH_MODE !== "live") { const urn = `urn:li:share:SIMULATED-${Date.now()}`; const log = await db.publishLog.create({ data: { draftId: draft.id, status: "SIMULATED", contentChecksum: currentChecksum, payload: JSON.stringify(payload), linkedInPostUrn: urn } }); await db.draft.update({ where: { id }, data: { status: "PUBLISHED", publishedAt: new Date() } }); await audit(user.id, "DRAFT_PUBLISHED_SIMULATED", "Draft", id, { urn }); return NextResponse.json({ mode: "simulated", log }); } const asset = draft.assets[0]; const result = await publishToLinkedIn(user.id, payload.commentary, asset ? { bytes: await readAsset(asset.storageKey), mimeType: asset.mimeType } : undefined); const log = await db.publishLog.create({ data: { draftId: draft.id, status: "SUCCEEDED", contentChecksum: currentChecksum, payload: JSON.stringify(payload), linkedInPostUrn: result.postUrn, linkedInAssetUrn: result.assetUrn } }); await db.draft.update({ where: { id }, data: { status: "PUBLISHED", publishedAt: new Date() } }); await audit(user.id, "DRAFT_PUBLISHED", "Draft", id, { urn: result.postUrn }); return NextResponse.json({ mode: "live", log }); } catch (error) { const message = error instanceof Error ? error.message : "PUBLISH_FAILED"; if (message !== "UNAUTHORIZED" && message !== "CSRF_FAILED") { const user = await getCurrentUser(request); const { id } = await params; const draft = user ? await db.draft.findFirst({ where: { id, userId: user.id } }) : null; if (draft) await db.publishLog.create({ data: { draftId: id, status: "FAILED", contentChecksum: draft.reviewedChecksum ?? "unknown", payload: JSON.stringify({ safe: true }), error: message } }); } return errorResponse(error); } }
